baseURL = 'https://lucascesar918.github.io'
languageCode = 'en-us'
title = 'Raw Memory'
theme = 'PaperMod'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"

  [[menu.main]]
    identifier = "about-me"
    name = "About Me"
    url = "/about/"

  [[menu.main]]
    identifier = "about-raw-memory"
    name = "What's this about?"
    url = "/posts/about-raw-memory/"

[params.assets]
favicon = "favicon.svg"
favicon16x16 = "favicon-16x16.png"
favicon32x32 = "favicon-32x32.png"
apple_touch_icon = "apple-touch-icon.png"
safari_pinned_tab = "safari-pinned-tab.svg"
theme_color = "#2e2e33"
msapplication_TileColor = "#2e2e33"
